// `movie-tv-en` source pack: English-language movie/TV editorial sources.
//
// Reusable bootstrap configuration — not tied to any site (GuiaTV or other).
// Every endpoint below was verified live on 2026-08-31 with the auctorio-bot
// user agent (HTTP 200 + parseable XML). Nothing here is a hardcoded
// publisher path in business logic: importing the pack creates ordinary
// ContentSource rows.

import type { SourcePackDefinition } from "./types";

export const MOVIE_TV_EN_PACK: SourcePackDefinition = {
  key: "movie-tv-en",
  name: "Movie & TV — English editorial pack",
  description:
    "Bootstrap configuration for major English-language movie/TV editorial sources (RSS/Atom feeds and news sitemaps). Optional pack; the database remains the runtime source of truth after import.",
  category: "movie-tv",
  language: "en",
  country: "US",
  optional: true,
  entries: [
    {
      id: "deadline",
      name: "Deadline",
      domain: "deadline.com",
      adapter: "rss",
      endpoint: "https://deadline.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.9,
      trust: 0.9,
      priority: 10,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 6, minIntervalMs: 10000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "trade"],
      notes: "Penske Media trade publication. RSS verified 2026-08-31.",
    },
    {
      id: "variety",
      name: "Variety",
      domain: "variety.com",
      adapter: "rss",
      endpoint: "https://variety.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.9,
      trust: 0.9,
      priority: 10,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 6, minIntervalMs: 10000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "trade"],
      notes: "Penske Media trade publication. RSS verified 2026-08-31.",
    },
    {
      id: "hollywoodreporter",
      name: "The Hollywood Reporter",
      domain: "www.hollywoodreporter.com",
      adapter: "rss",
      endpoint: "https://www.hollywoodreporter.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.9,
      trust: 0.9,
      priority: 10,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 6, minIntervalMs: 10000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "trade"],
      notes: "Penske Media trade publication. RSS verified 2026-08-31.",
    },
    {
      id: "indiewire",
      name: "IndieWire",
      domain: "www.indiewire.com",
      adapter: "rss",
      endpoint: "https://www.indiewire.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.85,
      trust: 0.85,
      priority: 9,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 6, minIntervalMs: 10000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "indie"],
      notes: "Penske Media. RSS verified 2026-08-31.",
    },
    {
      id: "collider",
      name: "Collider",
      domain: "collider.com",
      adapter: "rss",
      endpoint: "https://collider.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.75,
      trust: 0.75,
      priority: 8,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 8, minIntervalMs: 7500 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "fandom"],
      notes: "Valnet. Feed returns application/xml. RSS verified 2026-08-31.",
    },
    {
      id: "screenrant",
      name: "ScreenRant",
      domain: "screenrant.com",
      adapter: "rss",
      endpoint: "https://screenrant.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.7,
      trust: 0.7,
      priority: 8,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 8, minIntervalMs: 7500 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "fandom"],
      notes: "Valnet. RSS verified 2026-08-31.",
    },
    {
      id: "movieweb",
      name: "MovieWeb",
      domain: "movieweb.com",
      adapter: "rss",
      endpoint: "https://movieweb.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.65,
      trust: 0.65,
      priority: 7,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 8, minIntervalMs: 7500 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv"],
      notes: "Valnet. RSS verified 2026-08-31.",
    },
    {
      id: "comingsoon",
      name: "ComingSoon",
      domain: "www.comingsoon.net",
      adapter: "rss",
      endpoint: "https://www.comingsoon.net/feed",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.65,
      trust: 0.65,
      priority: 7,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 8, minIntervalMs: 7500 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv"],
      notes: "Evolve Media. RSS verified 2026-08-31.",
    },
    {
      id: "bloody-disgusting",
      name: "Bloody Disgusting",
      domain: "bloody-disgusting.com",
      adapter: "rss",
      endpoint: "https://bloody-disgusting.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.7,
      trust: 0.7,
      priority: 7,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 8, minIntervalMs: 7500 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["horror", "movies"],
      notes: "Serves XML with a text/html content-type header — parser ignores content-type. RSS verified 2026-08-31.",
    },
    {
      id: "slashfilm",
      name: "Slashfilm",
      domain: "www.slashfilm.com",
      adapter: "rss",
      endpoint: "https://www.slashfilm.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.7,
      trust: 0.7,
      priority: 8,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 8, minIntervalMs: 7500 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv"],
      notes: "Static Media. Feed returns text/xml. RSS verified 2026-08-31.",
    },
    {
      id: "denofgeek",
      name: "Den of Geek",
      domain: "www.denofgeek.com",
      adapter: "rss",
      endpoint: "https://www.denofgeek.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "GB",
      authority: 0.65,
      trust: 0.65,
      priority: 6,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 8, minIntervalMs: 7500 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "geek-culture"],
      notes: "RSS verified 2026-08-31.",
    },
    {
      id: "cinemablend",
      name: "CinemaBlend",
      domain: "www.cinemablend.com",
      adapter: "rss",
      endpoint: "https://www.cinemablend.com/rss",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.6,
      trust: 0.6,
      priority: 6,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true, maxItems: 40 },
      enabled: false,
      tags: ["movies", "tv"],
      notes: "Large full-site RSS (~800 KB); /feed returns 404 — /rss is the canonical endpoint. RSS verified 2026-08-31.",
    },
    {
      id: "theplaylist",
      name: "The Playlist",
      domain: "theplaylist.net",
      adapter: "rss",
      endpoint: "https://theplaylist.net/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.7,
      trust: 0.7,
      priority: 7,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 6, minIntervalMs: 10000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "indie"],
      notes: "Sitemaps blocked by Cloudflare (403) — feed only. RSS verified 2026-08-31.",
    },
    {
      id: "empire",
      name: "Empire",
      domain: "www.empireonline.com",
      adapter: "rss",
      endpoint: "https://rss.onebauer.media/api/feed-aggregator?hostname=https://www.empireonline.com",
      discoveryMethod: "link_alternate",
      category: "movie-tv",
      language: "en",
      country: "GB",
      authority: 0.8,
      trust: 0.8,
      priority: 8,
      refreshIntervalMinutes: 30,
      rateLimits: { maxRequestsPerMinute: 6, minIntervalMs: 10000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies"],
      notes: "No direct RSS; official feed discovered via <link rel=alternate> on the Empire homepage, served by Bauer Media's aggregator (rss.onebauer.media). Verified 2026-08-31.",
      restrictions: "Feed host is a third-party domain (rss.onebauer.media) — attribution remains to Empire/Bauer.",
    },
    {
      id: "bfi",
      name: "BFI",
      domain: "www.bfi.org.uk",
      adapter: "rss",
      endpoint: "https://www.bfi.org.uk/rss-feed",
      discoveryMethod: "link_alternate",
      category: "movie-tv",
      language: "en",
      country: "GB",
      authority: 0.85,
      trust: 0.85,
      priority: 7,
      refreshIntervalMinutes: 60,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "archive", "institute"],
      notes: "No /feed paths; official feed discovered via <link rel=alternate> on the BFI homepage. RSS verified 2026-08-31.",
    },
    {
      id: "filmcomment",
      name: "Film Comment",
      domain: "www.filmcomment.com",
      adapter: "rss",
      endpoint: "https://www.filmcomment.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.85,
      trust: 0.85,
      priority: 7,
      refreshIntervalMinutes: 60,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "criticism"],
      notes: "Film at Lincoln Center. RSS verified 2026-08-31.",
    },
    {
      id: "rogerebert",
      name: "RogerEbert.com",
      domain: "www.rogerebert.com",
      adapter: "rss",
      endpoint: "https://www.rogerebert.com/feed/",
      discoveryMethod: "official_rss",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.85,
      trust: 0.85,
      priority: 7,
      refreshIntervalMinutes: 60,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "reviews", "criticism"],
      notes: "Sitemaps blocked by Cloudflare (403) — feed only. RSS verified 2026-08-31.",
    },
    // ── Optional news-sitemap entries (disabled by default) ──────────────
    {
      id: "deadline-news-sitemap",
      name: "Deadline — News sitemap",
      domain: "deadline.com",
      adapter: "sitemap",
      endpoint: "https://deadline.com/news-sitemap.xml",
      discoveryMethod: "news_sitemap",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.9,
      trust: 0.9,
      priority: 5,
      refreshIntervalMinutes: 120,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "news-sitemap"],
      notes: "Google News sitemap declared in robots.txt. Verified 2026-08-31.",
    },
    {
      id: "variety-news-sitemap",
      name: "Variety — News sitemap",
      domain: "variety.com",
      adapter: "sitemap",
      endpoint: "https://variety.com/news-sitemap.xml",
      discoveryMethod: "news_sitemap",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.9,
      trust: 0.9,
      priority: 5,
      refreshIntervalMinutes: 120,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "news-sitemap"],
      notes: "Google News sitemap declared in robots.txt. Verified 2026-08-31.",
    },
    {
      id: "thr-news-sitemap",
      name: "The Hollywood Reporter — News sitemap",
      domain: "www.hollywoodreporter.com",
      adapter: "sitemap",
      endpoint: "https://www.hollywoodreporter.com/news-sitemap.xml",
      discoveryMethod: "news_sitemap",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.9,
      trust: 0.9,
      priority: 5,
      refreshIntervalMinutes: 120,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "tv", "news-sitemap"],
      notes: "News sitemap verified 2026-08-31 (robots.txt lists no sitemaps).",
    },
    {
      id: "indiewire-news-sitemap",
      name: "IndieWire — News sitemap",
      domain: "www.indiewire.com",
      adapter: "sitemap",
      endpoint: "https://www.indiewire.com/news-sitemap.xml",
      discoveryMethod: "news_sitemap",
      category: "movie-tv",
      language: "en",
      country: "US",
      authority: 0.85,
      trust: 0.85,
      priority: 5,
      refreshIntervalMinutes: 120,
      rateLimits: { maxRequestsPerMinute: 4, minIntervalMs: 15000 },
      robotsPolicy: { respect: true },
      extractionPolicy: { respectCopyright: true, extractArticleMetadataOnly: true },
      enabled: false,
      tags: ["movies", "news-sitemap"],
      notes: "Google News sitemap declared in robots.txt. Verified 2026-08-31.",
    },
  ],
  providers: [
    {
      key: "tmdb",
      name: "TMDB (The Movie Database)",
      providerType: "tmdb",
      baseUrl: "https://api.themoviedb.org/3",
      endpoint: "/trending/movie/week",
      credentialsRef: "TMDB_API_KEY",
      category: "movie-tv",
      enabled: false,
      configuration: {
        credentialScheme: "query_api_key",
        apiKeyParam: "api_key",
        itemsPath: "results",
        fields: {
          id: "id",
          title: "title",
          url: null,
          description: "overview",
          publishedAt: "release_date",
          image: "poster_path",
        },
        defaultParams: { language: "en-US" },
      },
      notes: "Free tier API key required. Endpoint verified live 2026-08-31 (401 without key).",
    },
    {
      key: "omdb",
      name: "OMDb API",
      providerType: "omdb",
      baseUrl: "https://www.omdbapi.com",
      endpoint: "/",
      credentialsRef: "OMDB_API_KEY",
      category: "movie-tv",
      enabled: false,
      configuration: {
        credentialScheme: "query_api_key",
        apiKeyParam: "apikey",
        itemsPath: null,
        fields: {
          id: "imdbID",
          title: "Title",
          url: null,
          description: "Plot",
          publishedAt: "Released",
        },
      },
      notes: "API key required (free tier). Endpoint verified live 2026-08-31 (401 without key).",
    },
    {
      key: "youtube",
      name: "YouTube Data API v3",
      providerType: "youtube",
      baseUrl: "https://www.googleapis.com/youtube/v3",
      endpoint: "/search",
      credentialsRef: "YOUTUBE_API_KEY",
      category: "movie-tv",
      enabled: false,
      configuration: {
        credentialScheme: "query_api_key",
        apiKeyParam: "key",
        itemsPath: "items",
        fields: {
          id: "id.videoId",
          title: "snippet.title",
          url: null,
          description: "snippet.description",
          publishedAt: "snippet.publishedAt",
        },
        defaultParams: { part: "snippet", type: "video" },
      },
      notes: "Google Cloud API key required. Endpoint verified live 2026-08-31 (403 without key).",
    },
    {
      key: "imdb_api",
      name: "IMDb Official API (AWS Data Exchange)",
      providerType: "imdb_api",
      baseUrl: null,
      endpoint: null,
      credentialsRef: "IMDB_API_KEY",
      category: "movie-tv",
      enabled: false,
      configuration: { credentialScheme: "bearer" },
      notes: "No public HTTP endpoint — IMDb's official programmatic access is a licensed AWS Data Exchange product. Marked unsupported until a license endpoint is configured.",
    },
  ],
};
